# Autogenerated configuration file for client connection parameters.
# File generated by mysql/conf/scripts/config-script.sh
[client]
database=CONF_DATABASE
host=CONF_HOST
port=CONF_PORT
user=CONF_USER
protocol=TCP

