#!/bin/bash

# Set the value of this variable to the prefix of your project.
PREFIX=CHARP

# Location of the ->SQL export generated by Power Architect
# (Uncomment and set accordingly if you are using Power Architect)
#SQL_EXPORT="$HOME/Documents/charp.sql"

# You may want to set this to a locale suitable to your country.
# This is for Spanish/Mexico, UTF-8 (CHARP uses UTF-8 all around,
# it is not recommended to switch to a diferent encoding).
DB_LOCALE=es_MX.utf8

# Locales under Windows have a different nomeclature and Postgres
# is system-dependent for locale specification. Uncomment and set 
# this accordingly if you are using Postgres for Windows.
#DB_LOCALE_WIN="Spanish, Mexico"

# Set this accordingly if you are using Cygwin and need to run
# the native executables instead of the ones from Cygwin.
# Otherwise, leave it commented.
#PGBINDIR="/cygdrive/c/Program Files/PostgreSQL/9.0/bin/"

# *** No further editing needed after this line. ***

CONF_DATABASE=${PREFIX}_PGDATABASE
CONF_HOST=${PREFIX}_PGHOST
CONF_PORT=${PREFIX}_PGPORT
CONF_USER=${PREFIX}_PGUSER
CONF_DIR=${PREFIX}DIR

export PGDATABASE=${!CONF_DATABASE}
export PGHOST=${!CONF_HOST}
export PGPORT=${!CONF_PORT}
export PGUSER=${!CONF_USER}

# Define <PREFIX>DIR in your bash_profile.
if [ ! -d "${!CONF_DIR}" ]; then
    echo Variable $CONF_DIR is not defined. >&2
    exit 1
fi

BASEDIR="${!CONF_DIR}"
TESTDIR="$BASEDIR/scripts/test"

# Directory where the project's SQL is found.
SQLDIR="$BASEDIR/sql"

# Under Cygwin, transform the directory to Windows notation, 
# since that's what the Windows-native Postgres requires for COPYs.
if [ $(uname -o) = 'Cygwin' ]; then
    IS_CYGWIN=1
    SQLDIR=$(sed 's#/cygdrive/\(\w\+\)/#\1:/#' <<< "$SQLDIR")
    DB_LOCALE=$DB_LOCALE_WIN
fi

# This obscure function runs psql with our own set of configuration variables
# and filters out unwanted psql NOTICEs.
function psql_filter {
    {
	psql \
	    -v conf_db=${!CONF_DATABASE} \
	    -v conf_user=${!CONF_USER} \
	    -v conf_locale_q="'$DB_LOCALE'" \
	    -v conf_sqldir_q1="'$SQLDIR" \
	    "$@" 2>&1 >&3 3>&- | grep -v ''\
'NOTICE:  CREATE TABLE / PRIMARY KEY \(will create implicit index\|crear. el .ndice impl.cito\)\|'\
'NOTICE:  \(constraint\|no existe la restricci.n\)\|'\
'NOTICE:  \(view\|la vista\)' >&2 3>&-
    } 3>&1
}
