
// This file has been generated by the GUI designer. Do not modify.
namespace monoCharp
{
	public partial class CharpGtkErrorDlg
	{
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Image imageIcon;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Label labelDesc;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Label labelMsg;
		private global::Gtk.Label labelSev;
		private global::Gtk.Button buttonClose;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget monoCharp.CharpGtkErrorDlg
			this.Name = "monoCharp.CharpGtkErrorDlg";
			this.Title = "CHARP Error";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.SkipTaskbarHint = true;
			// Internal child monoCharp.CharpGtkErrorDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(16));
			this.alignment2.TopPadding = ((uint)(8));
			this.alignment2.RightPadding = ((uint)(16));
			this.alignment2.BottomPadding = ((uint)(8));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.BottomPadding = ((uint)(16));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.imageIcon = new global::Gtk.Image ();
			this.imageIcon.WidthRequest = 64;
			this.imageIcon.HeightRequest = 64;
			this.imageIcon.Name = "imageIcon";
			this.imageIcon.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("monoCharp.error.png");
			this.alignment1.Add (this.imageIcon);
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(8));
			this.alignment3.TopPadding = ((uint)(32));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.labelDesc = new global::Gtk.Label ();
			this.labelDesc.Name = "labelDesc";
			this.labelDesc.Yalign = 0F;
			this.labelDesc.LabelProp = "Description";
			this.labelDesc.Wrap = true;
			this.labelDesc.Selectable = true;
			this.alignment3.Add (this.labelDesc);
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.BottomPadding = ((uint)(12));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.labelMsg = new global::Gtk.Label ();
			this.labelMsg.Name = "labelMsg";
			this.labelMsg.Xalign = 0F;
			this.labelMsg.Yalign = 0F;
			this.labelMsg.LabelProp = "<i><tt><small>Message</small></tt></i>";
			this.labelMsg.UseMarkup = true;
			this.labelMsg.Selectable = true;
			this.alignment4.Add (this.labelMsg);
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment4]));
			w8.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelSev = new global::Gtk.Label ();
			this.labelSev.Name = "labelSev";
			this.labelSev.Xalign = 0F;
			this.labelSev.LabelProp = "Severity";
			this.labelSev.Wrap = true;
			this.vbox2.Add (this.labelSev);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelSev]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.alignment2.Add (this.vbox2);
			w1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment2]));
			w11.Position = 0;
			// Internal child monoCharp.CharpGtkErrorDlg.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			this.AddActionWidget (this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonClose]));
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 348;
			this.Show ();
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
		}
	}
}
